/* Generated By:JJTree: Do not edit this line. ASTAttr_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAttr_type extends SimpleNode {
  public ASTAttr_type(int id) {
    super(id);
  }

  public ASTAttr_type(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf99d209e9760dcad696eba03a78c47a (do not edit this line) */
