/* Generated By:JJTree: Do not edit this line. ASTDotGraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTDotGraph extends SimpleNode {
  public ASTDotGraph(int id) {
    super(id);
  }

  public ASTDotGraph(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27681dd268d14f2c3973e623b77de149 (do not edit this line) */
