/* Generated By:JJTree: Do not edit this line. ASTDirected.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDirected extends SimpleNode {
  public ASTDirected(int id) {
    super(id);
  }

  public ASTDirected(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dcc16f6f6296b1f82e614892c05335ba (do not edit this line) */
