/* Generated By:JJTree: Do not edit this line. ASTEdge_stmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTEdge_stmt extends SimpleNode {
  public ASTEdge_stmt(int id) {
    super(id);
  }

  public ASTEdge_stmt(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fbc78e6b3b6d2ea2dab63bbb9d1d6880 (do not edit this line) */
