/* Generated By:JJTree: Do not edit this line. ASTGraphID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGraphID extends SimpleNode {
  public ASTGraphID(int id) {
    super(id);
  }

  public ASTGraphID(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c87849a36d0c6006741dc29698fd5ca (do not edit this line) */
