/* Generated By:JJTree: Do not edit this line. ASTPort.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTPort extends SimpleNode {
  public ASTPort(int id) {
    super(id);
  }

  public ASTPort(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2e3b98ca0b00cc0fb29282850edaccdd (do not edit this line) */
