/* Generated By:JJTree: Do not edit this line. ASTUndirected.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUndirected extends SimpleNode {
  public ASTUndirected(int id) {
    super(id);
  }

  public ASTUndirected(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea60d7726be09bc7f3177f5d591f4c2c (do not edit this line) */
