/* Generated By:JavaCC: Do not edit this line. Dot2DotTreeConstants.java Version 5.0 */
@SuppressWarnings("all")
public interface Dot2DotTreeConstants
{
  public int JJTDOTGRAPH = 0;
  public int JJTGRAPHID = 1;
  public int JJTGRAPH = 2;
  public int JJTVOID = 3;
  public int JJTNOVA = 4;
  public int JJTEDGE_STMT = 5;
  public int JJTNODE_ID = 6;
  public int JJTATTR_TYPE = 7;
  public int JJTA_LIST = 8;
  public int JJTSUBGRAPH = 9;
  public int JJTDIRECTED = 10;
  public int JJTUNDIRECTED = 11;
  public int JJTPORT = 12;


  public String[] jjtNodeName = {
    "DotGraph",
    "GraphID",
    "Graph",
    "void",
    "Nova",
    "Edge_stmt",
    "Node_id",
    "Attr_type",
    "A_list",
    "Subgraph",
    "Directed",
    "Undirected",
    "Port",
  };
}
/* JavaCC - OriginalChecksum=97f82cbf8cb566d0951cb1a5dee15f7f (do not edit this line) */
