/* Generated By:JJTree&JavaCC: Do not edit this line. Dot2DotConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Dot2DotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CARDINAL = 5;
  /** RegularExpression Id. */
  int GRAPH = 6;
  /** RegularExpression Id. */
  int DIGRAPH = 7;
  /** RegularExpression Id. */
  int STRICT = 8;
  /** RegularExpression Id. */
  int ATTR_SMT = 9;
  /** RegularExpression Id. */
  int SUBGRAPH = 10;
  /** RegularExpression Id. */
  int COMPASS_PT = 11;
  /** RegularExpression Id. */
  int NODE = 12;
  /** RegularExpression Id. */
  int ID = 13;
  /** RegularExpression Id. */
  int INTEGER = 14;
  /** RegularExpression Id. */
  int LF = 15;
  /** RegularExpression Id. */
  int EDGEOP_DIRECTED = 16;
  /** RegularExpression Id. */
  int EDGEOP_UNDIRECTED = 17;
  /** RegularExpression Id. */
  int LBRACKET = 18;
  /** RegularExpression Id. */
  int RBRACKET = 19;
  /** RegularExpression Id. */
  int LSQBRACK = 20;
  /** RegularExpression Id. */
  int RSQBRACK = 21;
  /** RegularExpression Id. */
  int COLON = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int EQUALS = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int DOT = 26;
  /** RegularExpression Id. */
  int DOUBLE_BACKSLASH = 27;
  /** RegularExpression Id. */
  int SLASH = 28;
  /** RegularExpression Id. */
  int MAIOR = 29;
  /** RegularExpression Id. */
  int LESS = 30;
  /** RegularExpression Id. */
  int LPARENTHESIS = 31;
  /** RegularExpression Id. */
  int RPARENTHESIS = 32;
  /** RegularExpression Id. */
  int MINUS = 33;
  /** RegularExpression Id. */
  int PLUS = 34;
  /** RegularExpression Id. */
  int PLICA = 35;
  /** RegularExpression Id. */
  int SYMBOLS = 36;
  /** RegularExpression Id. */
  int STRING = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\u0000\"",
    "\"#\"",
    "\"graph\"",
    "\"digraph\"",
    "\"strict\"",
    "<ATTR_SMT>",
    "\"subgraph\"",
    "<COMPASS_PT>",
    "\"node\"",
    "<ID>",
    "<INTEGER>",
    "\"\\n\"",
    "\"->\"",
    "\"--\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\".\"",
    "\"\\\\\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"(\"",
    "\")\"",
    "\"-\"",
    "\"+\"",
    "\"\\\'\"",
    "<SYMBOLS>",
    "<STRING>",
  };

}
