/* Generated By:JJTree&JavaCC: Do not edit this line. Dot2DotConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Dot2DotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CARDINAL = 5;
  /** RegularExpression Id. */
  int GRAPH = 6;
  /** RegularExpression Id. */
  int STRICT = 7;
  /** RegularExpression Id. */
  int ATTR_SMT = 8;
  /** RegularExpression Id. */
  int SUBGRAPH = 9;
  /** RegularExpression Id. */
  int COMPASS_PT = 10;
  /** RegularExpression Id. */
  int NODE = 11;
  /** RegularExpression Id. */
  int ID = 12;
  /** RegularExpression Id. */
  int INTEGER = 13;
  /** RegularExpression Id. */
  int LF = 14;
  /** RegularExpression Id. */
  int EDGEOP_DIRECTED = 15;
  /** RegularExpression Id. */
  int EDGEOP_UNDIRECTED = 16;
  /** RegularExpression Id. */
  int LBRACKET = 17;
  /** RegularExpression Id. */
  int RBRACKET = 18;
  /** RegularExpression Id. */
  int LSQBRACK = 19;
  /** RegularExpression Id. */
  int RSQBRACK = 20;
  /** RegularExpression Id. */
  int COLON = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int EQUALS = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int DOT = 25;
  /** RegularExpression Id. */
  int DOUBLE_BACKSLASH = 26;
  /** RegularExpression Id. */
  int SLASH = 27;
  /** RegularExpression Id. */
  int MAIOR = 28;
  /** RegularExpression Id. */
  int LESS = 29;
  /** RegularExpression Id. */
  int LPARENTHESIS = 30;
  /** RegularExpression Id. */
  int RPARENTHESIS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int PLUS = 33;
  /** RegularExpression Id. */
  int PLICA = 34;
  /** RegularExpression Id. */
  int SYMBOLS = 35;
  /** RegularExpression Id. */
  int STRING = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\u0000\"",
    "\"#\"",
    "<GRAPH>",
    "\"strict\"",
    "<ATTR_SMT>",
    "\"subgraph\"",
    "<COMPASS_PT>",
    "\"node\"",
    "<ID>",
    "<INTEGER>",
    "\"\\n\"",
    "\"->\"",
    "\"--\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\".\"",
    "\"\\\\\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"(\"",
    "\")\"",
    "\"-\"",
    "\"+\"",
    "\"\\\'\"",
    "<SYMBOLS>",
    "<STRING>",
  };

}
