/* Generated By:JavaCC: Do not edit this line. Dot2DotTreeConstants.java Version 5.0 */
public interface Dot2DotTreeConstants
{
  public int JJTDOTGRAPH = 0;
  public int JJTVOID = 1;
  public int JJTTEST = 2;
  public int JJTNOVA = 3;
  public int JJTEDGE_STMT = 4;
  public int JJTNODE_ID = 5;
  public int JJTA_LIST = 6;
  public int JJTSUBGRAPH = 7;
  public int JJTDIRECTED = 8;
  public int JJTUNDIRECTED = 9;
  public int JJTPORT = 10;


  public String[] jjtNodeName = {
    "DotGraph",
    "void",
    "test",
    "Nova",
    "Edge_stmt",
    "Node_id",
    "A_list",
    "Subgraph",
    "Directed",
    "Undirected",
    "Port",
  };
}
/* JavaCC - OriginalChecksum=99b5e7ab1982f44a094746b2e2b21ffe (do not edit this line) */
