/* Generated By:JavaCC: Do not edit this line. Dot2DotTreeConstants.java Version 5.0 */
public interface Dot2DotTreeConstants
{
  public int JJTDOTGRAPH = 0;
  public int JJTVOID = 1;
  public int JJTTEST = 2;
  public int JJTNOVA = 3;
  public int JJTEDGE_STMT = 4;
  public int JJTNODE_ID = 5;
  public int JJTATTR_TYPE = 6;
  public int JJTA_LIST = 7;
  public int JJTSUBGRAPH = 8;
  public int JJTDIRECTED = 9;
  public int JJTUNDIRECTED = 10;
  public int JJTPORT = 11;


  public String[] jjtNodeName = {
    "DotGraph",
    "void",
    "test",
    "Nova",
    "Edge_stmt",
    "Node_id",
    "Attr_type",
    "A_list",
    "Subgraph",
    "Directed",
    "Undirected",
    "Port",
  };
}
/* JavaCC - OriginalChecksum=4d4405bf9d5b58923e0b924e400ad6b0 (do not edit this line) */
